on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    env:
      JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.442-6/x64/Contents/Home/
    steps:
    - uses: actions/checkout@v4
    - run: ant generate-all compile_native
