on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: echo $JAVA_HOME
    - run: echo $JAVA_HOME_8_X64
    - run: ant generate-all compile_native
