on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - run: |
        git clone --filter=blob:none --no-checkout https://github.com/phracker/MacOSX-SDKs
        cd MacOSX-SDKs
        git sparse-checkout init --cone
        git sparse-checkout add MacOSX10.9.sdk
        git checkout master
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: echo $JAVA_HOME
    - run: echo $JAVA_HOME_8_X64
    - run: ant generate-all compile_native
