on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: sudo apt-get install libxrandr-dev libxcursor-dev libxxf86vm-dev
    - run: ant generate-all compile_native
