on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
#   env:
#     JAVA_HOME: $JAVA_HOME_8_X64
    steps:
    - uses: actions/checkout@v4
    - run: |
        export JAVA_HOME=/usr/libexec/java_home -v 1.8
        ant generate-all compile_native
