on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo $SHELL
        % nano ~/.bash_profile
        export JAVA_HOME=$(/usr/libexec/java_home -v1.8)
        % source ~/.bash_profile
        echo $JAVA_HOME
    - run: ant generate-all compile_native
