on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: sudo apt-get install libx11-dev libxext-dev libxcursor-dev libxrandr-dev libxxf86vm-dev libpthread-stubs0-dev libxt-dev libxaw7-dev libxmu-dev
    - run: ant generate-all compile_native
