on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo $SHELL
        echo export "JAVA_HOME=\$(/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64/Contents/Home/)" >> ~/.bash_profile
        echo export "JAVA_HOME=\$(/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64/Contents/Home/)" >> ~/.zshrc
        echo $JAVA_HOME
    - run: ant generate-all compile_native
