on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - run: |
        pwd
        ls *
        git clone --filter=blob:none --no-checkout https://github.com/phracker/MacOSX-SDKs
        ls *
        cd MacOSX-SDKs
        ls *
        git sparse-checkout set --cone
        ls *
        git checkout master
        ls *
        git sparse-checkout set MacOSX10.9.sdk
        ls *
#   - uses: actions/checkout@v4
#   - uses: actions/setup-java@v4
#     with:
#       distribution: 'zulu'
#       java-version: '8'
#   - run: echo $JAVA_HOME
#   - run: echo $JAVA_HOME_8_X64
#   - run: ant generate-all compile_native
