on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - run: ls /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.442-6/x64/Contents/Home/
    - run: ls /System/Library/Frameworks/JavaVM.framework/Versions/Current
