on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: xcode-select -print-path
    - run: export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
    - run: ant generate-all compile_native
    - run: xcrun --show-sdk-path
    - run: xcrun --sdk macosx --show-sdk-path
