on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        distribution: 'zulu'
        java-version: '8'
    - run: ant generate-all compile_native
