on: workflow_dispatch
jobs:
  build-windows-x86_64-native:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - uses: ilammy/msvc-dev-cmd@v1
    - run: ant generate-all compile_native
    - uses: actions/cache/save@v4
      with:
        path: libs/lwjgl64.dll
        key: ${{ runner.os }}-${{ hashFiles('libs/lwjgl64.dll') }}
        enableCrossOsArchive: true
  build-windows-x86-native:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
        architecture: x86
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    - run: ant generate-all compile_native
    - uses: actions/cache/save@v4
      with:
        path: libs/lwjgl.dll
        key: ${{ runner.os }}-${{ hashFiles('libs/lwjgl.dll') }}
        enableCrossOsArchive: true
